export const MISSING_ACCESS_TOKEN_ERROR_CODE = 'MISSING_ACCESS_TOKEN_ERROR';
export const DUPLICATED_USERNAME_ERROR_CODE = 'DUPLICATED_USERNAME_ERROR';
export const UNAUTHORIZED_ERROR_CODE = 'UNAUTHORIZED_ERROR';
export const USER_NOT_FOUND_ERROR_CODE = 'USER_NOT_FOUND_ERROR';
export const INVALID_CREDENTIALS_ERROR_CODE = 'INVALID_CREDENTIALS_ERROR';
export const USER_ONLY_ENDPOINT_ERROR_CODE = 'USER_ONLY_ENDPOINT_ERROR';
export const ADMIN_ONLY_ENDPOINT_ERROR_CODE = 'ADMIN_ONLY_ENDPOINT_ERROR';
export const INVALID_OR_EXPIRED_TOKEN_ERROR_CODE =
  'INVALID_OR_EXPIRED_TOKEN_ERROR';
export const INVALID_DTO_FIELDS_ERROR_CODE = 'INVALID_DTO_FIELDS_ERROR';
export const INVALID_CONFIGURATION_ERROR_CODE = 'INVALID_CONFIGURATION_ERROR';
export const INTERNAL_ERROR_CODE = 'INTERNAL_ERROR';
export const MESSAGE_CHANNEL_TYPE_NOT_AVAILABLE =
  'MESSAGE_CHANNEL_TYPE_NOT_AVAILABLE_ERROR';
export const BOT_NOT_FOUND_ERROR = 'BOT_NOT_FOUND_ERROR';
export const BOT_INTENT_NOT_FOUND_ERROR = 'BOT_INTENT_NOT_FOUND_ERROR';
export const CHAT_NOT_FOUND_ERROR = 'CHAT_NOT_FOUND_ERROR';
export const CHAT_MESSAGE_NOT_FOUND_ERROR = 'CHAT_MESSAGE_NOT_FOUND_ERROR';
export const MESSAGE_CHANNEL_NOT_FOUND_ERROR =
  'MESSAGE_CHANNEL_NOT_FOUND_ERROR';
export const PAIRING_REQUEST_TIMEDOUT = 'PAIRING_REQUEST_TIMEDOUT';
export const PAIRING_CODE_EXPIRED = 'PAIRING_CODE_EXPIRED';
export const INVALID_PAIRING_CODE = 'INVALID_PAIRING_CODE';
export const MESSAGE_CHANNEL_ALREADY_PAIRED = 'MESSAGE_CHANNEL_ALREADY_PAIRED';
export const MESSAGE_CHANNEL_NOT_PAIRED = 'MESSAGE_CHANNEL_NOT_PAIRED';
export const SESSION_NOT_FOUND_ERROR = 'SESSION_NOT_FOUND_ERROR';
export const LANGUAGE_MODEL_MISCONFIGURED_ERROR =
  'LANGUAGE_MODEL_MISCONFIGURED_ERROR';
export const LANGUAGE_MODEL_QUOTA_EXCEEDED_ERROR =
  'LANGUAGE_MODEL_QUOTA_EXCEEDED_ERROR';
export const LANGUAGE_MODEL_SERVER_ERROR = 'LANGUAGE_MODEL_SERVER_ERROR';
export const LANGUAGE_MODEL_UNEXPECTED_ERROR =
  'LANGUAGE_MODEL_UNEXPECTED_ERROR';
export const FAILED_TO_GENERATE_NAME_AND_TAG_ERROR =
  'FAILED_TO_GENERATE_NAME_AND_TAG_ERROR';
