export const MISSING_ACCESS_TOKEN_ERROR_CODE = 'MISSING_ACCESS_TOKEN_ERROR';
export const DUPLICATED_USERNAME_ERROR_CODE = 'DUPLICATED_USERNAME_ERROR';
export const UNAUTHORIZED_ERROR_CODE = 'UNAUTHORIZED_ERROR';
export const USER_NOT_FOUND_ERROR_CODE = 'USER_NOT_FOUND_ERROR';
export const INVALID_CREDENTIALS_ERROR_CODE = 'INVALID_CREDENTIALS_ERROR';
export const USER_ONLY_ENDPOINT_ERROR_CODE = 'USER_ONLY_ENDPOINT_ERROR';
export const ADMIN_ONLY_ENDPOINT_ERROR_CODE = 'ADMIN_ONLY_ENDPOINT_ERROR';
export const INVALID_OR_EXPIRED_TOKEN_ERROR_CODE =
  'INVALID_OR_EXPIRED_TOKEN_ERROR';
export const INVALID_DTO_FIELDS_ERROR_CODE = 'INVALID_DTO_FIELDS_ERROR';
export const INVALID_CONFIGURATION_ERROR_CODE = 'INVALID_CONFIGURATION_ERROR';
export const INTERNAL_ERROR_CODE = 'INTERNAL_ERROR';
