export const MESSAGE_CHANNEL_REPOSITORY = Symbol('MESSAGE_CHANNEL_REPOSITORY');
export const CHAT_MESSAGE_REPOSITORY = Symbol('CHAT_MESSAGE_REPOSITORY');
export const CHAT_REPOSITORY = Symbol('CHAT_REPOSITORY');
export const MESSAGE_CHANNEL_SERVICE = Symbol('MESSAGE_CHANNEL_SERVICE');
