import { useUpdateBotIntentMutation } from "@/lib/api/client";
import {
  Box,
  Button,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  TextField,
} from "@mui/material";
import React, { useEffect, useState } from "react";
import ApiErrorAlert from "../alerts/api-error-alert.component";
import { BotIntentResponse, UpdateBotIntentRequest } from "@/lib/api/dtos";

export default function UpdateBotIntentModal({
  open,
  onClose,
  botIntent,
  afterMutate,
}: {
  open: boolean;
  onClose: () => void;
  botIntent?: BotIntentResponse | null;
  afterMutate?: (data: BotIntentResponse) => void;
}) {
  const [updateBotIntent, { isLoading: isUpdating, error: updateError }] =
    useUpdateBotIntentMutation();

  const isLoading = isUpdating;
  const error = updateError;

  const [tag, setTag] = useState("");
  const [name, setName] = useState("");
  const [trigger, setTrigger] = useState("");
  const [response, setResponse] = useState("");

  useEffect(() => {
    if (open && botIntent) {
      setTag(botIntent.tag);
      setName(botIntent.name);
      setTrigger(botIntent.trigger);
      setResponse(botIntent.response);
    } else if (!open) {
      setTag("");
      setName("");
      setTrigger("");
      setResponse("");
    }
  }, [open, botIntent]);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!botIntent) return;

    const updateData: UpdateBotIntentRequest = {};
    if (name !== botIntent.name) updateData.name = name;
    if (trigger !== botIntent.trigger) updateData.trigger = trigger;
    if (response !== botIntent.response) updateData.response = response;

    updateBotIntent({
      botId: botIntent.botId,
      intentId: botIntent.id,
      data: updateData,
    }).then(({ data, error }) => {
      if (error) return;
      onClose();
      if (afterMutate && data) afterMutate(data);
    });
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      aria-labelledby="modal-modal-title"
      aria-describedby="modal-modal-description"
      component={"form"}
      fullWidth
      onSubmit={handleSubmit}
      maxWidth="sm"
    >
      <DialogTitle id="modal-modal-title">
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          Update Bot Intent
          {isLoading && <CircularProgress size={24} sx={{ ml: 1 }} />}
        </Box>
      </DialogTitle>
      <DialogContent>
        <Box sx={{ mt: 2, display: "flex", flexDirection: "column", gap: 2 }}>
          <TextField
            label="Name"
            variant="outlined"
            fullWidth
            required
            value={name}
            onChange={(e) => setName(e.target.value)}
            helperText="A descriptive name for this intent"
          />
          <TextField
            label="Trigger"
            variant="outlined"
            fullWidth
            required
            value={trigger}
            onChange={(e) => setTrigger(e.target.value)}
            placeholder="e.g., 'When does the store open?'"
            helperText="The message that will trigger this intent"
          />
          <TextField
            label="Response"
            variant="outlined"
            fullWidth
            required
            multiline
            rows={3}
            value={response}
            onChange={(e) => setResponse(e.target.value)}
            placeholder="e.g., 'The store opens at 9 AM every day except Sunday.'"
            helperText="The bot's response when this intent is triggered"
          />
          <TextField
            label="Tag"
            variant="outlined"
            fullWidth
            size="small"
            disabled
            value={tag}
            onChange={(e) => setTag(e.target.value)}
            helperText="Generated by the system. Cannot be changed!"
          />
        </Box>
        {error && !isLoading && (
          <ApiErrorAlert
            error={error}
            defaultMessage="Failed to update bot intent"
          />
        )}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} color="inherit" sx={{ color: "grey" }}>
          Cancel
        </Button>
        <Button
          disabled={isLoading}
          loading={isLoading}
          variant="contained"
          color="primary"
          type="submit"
        >
          Update
        </Button>
      </DialogActions>
    </Dialog>
  );
}
